1주차. Numpy

(1) Basic operation

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,4,5],[6,7,8.0]])
print(A)
print(B)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[3. 4. 5.]
 [6. 7. 8.]]


In [2]:
print(A.ndim) # 차원
print(A.shape) # 행, 열의 수
print(A.size) # 데이터 개수
print(A.T) # transpose
print(A.dtype) # 데이터 타입
print(B.dtype) # float64

A = np.array([[1,2,3],[4,5,6]], dtype=np.float64) # 데이터 타입 변경 가능
print(A.dtype)

2
(2, 3)
6
[[1 4]
 [2 5]
 [3 6]]
int32
float64
float64


In [3]:
np.arange(0,1,0.2) # (start), stop, (step)  # 마지막 stop 수는 포함하지 않아!!!!!!!

array([0. , 0.2, 0.4, 0.6, 0.8])

In [4]:
np.linspace(0,10, num=11) # start, stop, number   # 마지막 stop 수 포함해!!!!!

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
A = np.arange(1,21)
B = A.reshape([4,5])
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
A = np.ones([3,2])
B = np.ones([2,3])
np.dot(A, B)
B @ A

array([[3., 3.],
       [3., 3.]])

(2) Slicing

In [7]:
A = np.arange(1,21)
B = A.reshape([4,5])

In [8]:
# row 가져오기 (B[:2, :] 이런식으로 해도 )
B[:2] # 0번째 element부터 2번째 element 바로 앞까지
B[-2:] # 마지막 원소 index가 -1 # 전전 원소부터 끝까지
print(B[1:2]) # matrix # 1번째 원소만 가져오되 차원 유지 # array([[6,7,8,9,10]])
print(B[1])   # vector # 1번째 원소만 가져오기. 차원 낮아짐 # array([6,7,8,9,10])

[[ 6  7  8  9 10]]
[ 6  7  8  9 10]


In [9]:
a = np.arange(10)
print(a)
print(a[2:3]) # slicing = dim이 바뀌지 않는다.
print(a[2]) # dim이 바뀐다. element만 가져온다.

[0 1 2 3 4 5 6 7 8 9]
[2]
2


In [10]:
# column 가져오기
print(B[:, 1:2]) # dim 유지
print(B[:, 1])   # dim 변경 # element만 가져

[[ 2]
 [ 7]
 [12]
 [17]]
[ 2  7 12 17]


In [11]:
B = np.arange(20).reshape([5,4])
# B[[0,1,3],[0,2]] 불가능해

In [12]:
B[[0,1,3]][:,[0,2]] # step by step으로 추출해야해

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])

(3) Broadcasting

**Broadcasting** :

1) Rule 1 : 차원이 다르다
차원이 낮은 shape에 좌측에 1을 패딩
ex) (3,) -> (1,3), [1,2,3] -> [[1,2,3]]

2) Rule 2 : shape이 다르다
shape이 1인 것을 늘려 다른 shape에 맞춘다.
ex) (1,3) + (2,1) -> (1->2,3) + (2,1->3)

In [13]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([1,2,3])
A + B
# B가 [1,2,3] -> [[1,2,3]] (Rule 1: 패딩해 dimension 맞춰줘)
# [[1,2,3]] -> [[1,2,3],[1,2,3]] (Rule 2: shape이 1인 것을 늘려 shape 맞춰줘)

array([[2, 4, 6],
       [5, 7, 9]])

axis = 0 : column 별로 // axis = 1 : row 별로

In [14]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.sum(axis=0)) # column sum
print(a.sum(axis=1)) # row sum
print(a.min())
print(a.min(axis=0)) # column min

[[0.12781553 0.18274252 0.40129224]
 [0.29638551 0.89875122 0.64193235]]
2.5489193628856763
[0.42420103 1.08149373 1.04322459]
[0.71185028 1.83706908]
0.1278155277835875
[0.12781553 0.18274252 0.40129224]


In [15]:
A = np.array([[2,4,1],
              [3,1,4]])
print(A.cumsum())
print(A.cumsum(axis=0))

[ 2  6  7 10 11 15]
[[2 4 1]
 [5 5 5]]


In [16]:
# example
Car = np.array([[1,2,6,4,3,4,8],
                [10,13,21,32,21,45,47]])
City_mean = Car.mean(axis=1) # row별로의 평균. (2,)의 크기
# Car - [4, 27] : [2,7]에서 [2,]를 빼는건 error -> (2,7)에서 (1,2) 빼면 불가능
# Car - [[4],[27]] : (2,7) 에서 (2,1) 빼는건 broadcasting 이루어져 가능
Car - City_mean.reshape([2,1])

array([[ -3.,  -2.,   2.,   0.,  -1.,   0.,   4.],
       [-17., -14.,  -6.,   5.,  -6.,  18.,  20.]])

(4) Multi array

In [17]:
A = np.array([[[10,20,30,40],[50,60,70,80]]])
A.shape

(1, 2, 4)

In [18]:
A[0,1,2] # 70

70

In [19]:
B = np.array([[[10,20],[30,40],[50,60],[70,80]]])
B.shape

(1, 4, 2)

In [20]:
B[0,2,1]

60

(5) Multi array part 2

In [21]:
A = np.array([[[1,2,3,4],[5,6,7,8]],
              [[10,20,30,40],[50,60,70,80]]])
A.shape

(2, 2, 4)

In [22]:
A[:,:,0]

array([[ 1,  5],
       [10, 50]])

In [23]:
A[:,:,:1]

array([[[ 1],
        [ 5]],

       [[10],
        [50]]])

In [24]:
A[0,:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
A[:1,:,:]

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [29]:
A = np.array([[[340,300,100,120],[270,250,150,110],[370,350,250,120]],
              [[390,200,200,130],[370,290,140,140],[470,390,240,150]]])
A.shape              

(2, 3, 4)

In [31]:
A.sum(axis=2) # each person each year -> axis=2 (4개 각각 합하도록)

array([[ 860,  780, 1090],
       [ 920,  940, 1250]])

In [32]:
A.sum(axis=0) # person 방향으로 더해라 # year, item별로

array([[730, 500, 300, 250],
       [640, 540, 290, 250],
       [840, 740, 490, 270]])

In [33]:
A.sum(axis=1)

array([[ 980,  900,  500,  350],
       [1230,  880,  580,  420]])

(6) Joining array

In [34]:
A = np.array([[1,2,3],[10,20,30]])
B = np.array([[4,5,6],[40,50,60]])

np.concatenate : dimension이 바뀌지 않는다!

In [36]:
np.concatenate((A, B), axis=0) # 아래로 붙여 shape에서 행 수의 합 # (2,3) + (2,3) => (4,3)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60]])

In [37]:
np.concatenate((A, B), axis=1) # (2,3) + (2,3) => (2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

np.stack : dimension 증가!

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [41]:
np.stack((a,b), axis=0) # (1,2,2) + (1,2,2) => (2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.stack((a,b), axis=1) # (2,1,2) + (2,1,2) => (2,2,2)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [43]:
# np.stack((a,b), axis=1)과 동일한 과정
a_r = a.reshape((2,1,2)) # axis=1 부분을 1로 하고 reshape한 것을 concat해
b_r = b.reshape((2,1,2))
np.concatenate((a_r, b_r), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])