In [1]:
!pip install torch

   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ------ --------------------------------- 1.0/6.2 MB 5.6 MB/s eta 0:00:01
   --------------- ------------------------ 2.4/6.2 MB 5.8 MB/s eta 0:00:01
   ----------------------- ---------------- 3.7/6.2 MB 5.9 MB/s eta 0:00:01
   ------------------------------ --------- 4.7/6.2 MB 5.9 MB/s eta 0:00:01
   -------------------------------------- - 6.0/6.2 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 5.7 MB/s eta 0:00:00
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.2
    Uninstalling sympy-1.13.2:
      Successfully uninstalled sympy-1.13.2


In [3]:
import torch

In [4]:
A = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
print(A.shape)
print(A.ndim)
print(A.device)
print(A.dtype) # torch.int64

torch.Size([2, 3])
2
cpu
torch.int64


In [12]:
B = torch.tensor([[1,2,3],[4,5,6.0]])
print(B.dtype) # torch.float64

torch.float32


In [14]:
# torch.diag([3,2,5]) # error # input이 tensor이어야해
torch.diag(torch.tensor([3,2,5]))

tensor([[3, 0, 0],
        [0, 2, 0],
        [0, 0, 5]])

In [16]:
A = torch.ones((3,2))
B = torch.ones((2,3))
torch.matmul(A, B) # A@B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [18]:
A = torch.tensor([[1,2,3],[10,20,30]])
B = torch.tensor([[4,5,6],[40,50,60]])
torch.cat((A,B), axis=0) # 아래로 붙여 # (4,3)
torch.cat((A,B), axis=1) # (2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [10, 20, 30, 40, 50, 60]])

(5) Datasets and Dataloader

In [119]:
from torch.utils.data import TensorDataset, DataLoader

In [121]:
x = torch.tensor([[1.0, 5.0],
                  [-1.0, 2.3],
                  [1.1, 3.0],
                  [-0.5, 10.0],
                  [-3.0, 2.5]])
x

tensor([[ 1.0000,  5.0000],
        [-1.0000,  2.3000],
        [ 1.1000,  3.0000],
        [-0.5000, 10.0000],
        [-3.0000,  2.5000]])

In [123]:
y = torch.tensor([5.0, 1.0, 3.0, 5.5, 1.3])
y

tensor([5.0000, 1.0000, 3.0000, 5.5000, 1.3000])

In [125]:
mydata = TensorDataset(x,y) # mydata를 불러줘 하면 볼 수 없어 # 인자로는 tensor만 넣을 수 있어!

In [127]:
mydata[0] # 0번째 사람의 x와 y

(tensor([1., 5.]), tensor(5.))

In [129]:
mydata[0:2]

(tensor([[ 1.0000,  5.0000],
         [-1.0000,  2.3000]]),
 tensor([5., 1.]))

In [131]:
xx, yy = mydata[0:3]

In [133]:
xx # 설명변수

tensor([[ 1.0000,  5.0000],
        [-1.0000,  2.3000],
        [ 1.1000,  3.0000]])

In [135]:
yy # 반응변수

tensor([5., 1., 3.])

In [137]:
len(mydata)

5

In [147]:
myloader = DataLoader(mydata, batch_size=2, shuffle=True) # batch는 묶음수, shuffle는 랜덤섞을지

In [149]:
for xx, yy in myloader:
    print(yy)

tensor([1.3000, 3.0000])
tensor([5.0000, 5.5000])
tensor([1.])


(6) Derivatives

In [160]:
x = torch.tensor(1., requires_grad=True)
y = 2*x**3 + x
y.backward()
x.grad # x로 미분한 값

tensor(7.)

In [162]:
x = torch.tensor(2.0, requires_grad =True)
y = x**3+3
y.backward()
x.grad

tensor(12.)

In [164]:
x = torch.tensor(1., requires_grad=True)
y = torch.tensor(2., requires_grad=True)
f = 2*x**3 + y**2
f.backward()
print(x.grad, y.grad) # df/dx에 x 값 대입, df/dy에 y 대

tensor(6.) tensor(4.)


In [166]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
f = 3*x**2 + 6*y + z # f=11을 계산하고, df/dx, df/dy, df/dz를 계산할 준비를 함.
f.backward() # df/dx=6, df/dy=6, df/dz=1을 계산하고, 어딘가에 저장함.
print(x.grad, y.grad, z.grad)

tensor(6.) tensor(6.) tensor(1.)


In [172]:
x = torch.tensor(1.0, requires_grad=True)
y = 2*x**3 + x
z = torch.exp(y)
z.backward()
x.grad # (6*x**2 + 1) * exp(2*x**3+x) 에 1 대입

tensor(140.5988)

(7) Partial differentiation and Gradients

In [196]:
x = torch.tensor([1.0, 2.0], requires_grad=True)
f = (x[0] + 2 * x[1] **3)**2 # f 계산하고, df/dx 미분 준
f.backward()
x.grad

tensor([ 34., 816.])

In [198]:
t = torch.tensor(1.0, requires_grad=True)
g = torch.stack([torch.sin(t), torch.cos(t)])
f = g[0]**2 + 2*g[1]
f.backward()
t.grad

tensor(-0.7736)

In [200]:
t = torch.tensor([1.0, 2.0], requires_grad=True)
g = torch.stack([torch.sin(t[0])+torch.cos(t[1]), torch.cos(t[0])])
f = g[0]**2 + 2*g[1]
f.backward()
t.grad

tensor([-1.2233, -0.7735])