(1) Pytorch Lab : Basic operation

In [300]:
import torch
import numpy as np

In [301]:
torch.rand([2,2])  # Unif[0,1]에서 random number

tensor([[0.3925, 0.9289],
        [0.4601, 0.8203]])

In [302]:
a = torch.tensor([2]).to('cpu')
a.device

device(type='cpu')

In [303]:
tensor = torch.rand([4, 4])
tensor

tensor([[0.8929, 0.1146, 0.1940, 0.5099],
        [0.9805, 0.4789, 0.0567, 0.9517],
        [0.4771, 0.7531, 0.9178, 0.2216],
        [0.3274, 0.1647, 0.3386, 0.1719]])

In [304]:
t1 = torch.cat([tensor, tensor], axis=0) #join a sequence of arrays along an existing axis.
print(t1.shape)
t2 = torch.cat([tensor, tensor], axis=1) #join a sequence of arrays along an existing axis.
print(t2.shape)
# numpy에서는 np.concatenate

torch.Size([8, 4])
torch.Size([4, 8])


In [305]:
t3 = torch.stack([tensor, tensor], axis=0) #Join a sequence of arrays along a new axis.
print(t3.shape) # (1,4,4) + (1,4,4) = (2,4,4)

t4 = torch.stack([tensor, tensor], axis=2) #Join a sequence of arrays along a new axis.
print(t4.shape) # (4,4,1) + (4,4,1) = (4,4,2)
# numpy에서도 np.stack

torch.Size([2, 4, 4])
torch.Size([4, 4, 2])


In [306]:
a1 = torch.tensor([[1,1],
                   [0,2.0]])
a2 = torch.tensor([[1,1],
                   [0,2.0]])

In [307]:
print(a1@a2)
a1.matmul(a2)

tensor([[1., 3.],
        [0., 4.]])


tensor([[1., 3.],
        [0., 4.]])

In [308]:
agg = a1.sum()
agg.item() # tensor 앞에 없이 값만 가져오도록
# 원소 한 개짜리일때만 가능!

4.0

In [309]:
t = torch.ones(5)
print(t)
a = t.numpy()
print(a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [310]:
t[3]=10
print(f"t: {t}")
print(f"a: {a}")  # 원본이 바뀌어 복사본도 바뀌었다

t: tensor([ 1.,  1.,  1., 10.,  1.])
a: [ 1.  1.  1. 10.  1.]


In [311]:
n = np.ones(5)
t = torch.tensor(n)

In [312]:
n[1]=10
print(t) # 원본 그대로 유지돼
print(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[ 1. 10.  1.  1.  1.]


In [313]:
length = 5
x = 2*torch.rand([length,2])
x

tensor([[1.2573, 1.2902],
        [0.3540, 1.2680],
        [1.7735, 1.1680],
        [0.5555, 0.5422],
        [0.6866, 0.6735]])

In [314]:
y = torch.sum(x, axis=1)
y

tensor([2.5475, 1.6220, 2.9415, 1.0977, 1.3600])

In [315]:
from torch.utils.data import TensorDataset, DataLoader
mydata = TensorDataset(x,y) # 길이가 같은 x,y를 묶어준다

In [316]:
mydata[0]

(tensor([1.2573, 1.2902]), tensor(2.5475))

In [317]:
xx, yy = mydata[1:3]
print(xx, yy)

tensor([[0.3540, 1.2680],
        [1.7735, 1.1680]]) tensor([1.6220, 2.9415])


In [318]:
# Ex 1
from torch.utils.data import TensorDataset, DataLoader
X = torch.rand([5,2])
Y = torch.randint(low=0, high=10, size=[5])
print(X, Y)

tensor([[0.4662, 0.9467],
        [0.3608, 0.0373],
        [0.0852, 0.7634],
        [0.9327, 0.1092],
        [0.3002, 0.0648]]) tensor([7, 0, 0, 9, 2])


In [319]:
mydata = TensorDataset(X, Y)

In [320]:
trainloader = DataLoader(dataset = mydata, batch_size=1, shuffle=False)

In [321]:
for xx, yy in trainloader:
    print('xx=', xx, ',     yy =', yy)

xx= tensor([[0.4662, 0.9467]]) ,     yy = tensor([7])
xx= tensor([[0.3608, 0.0373]]) ,     yy = tensor([0])
xx= tensor([[0.0852, 0.7634]]) ,     yy = tensor([0])
xx= tensor([[0.9327, 0.1092]]) ,     yy = tensor([9])
xx= tensor([[0.3002, 0.0648]]) ,     yy = tensor([2])


In [322]:
trainloader = DataLoader(dataset = mydata, batch_size=2, shuffle=True)

In [323]:
for xx, yy in trainloader:
    print('xx=', xx, ',     yy =', yy)

xx= tensor([[0.3002, 0.0648],
        [0.4662, 0.9467]]) ,     yy = tensor([2, 7])
xx= tensor([[0.9327, 0.1092],
        [0.3608, 0.0373]]) ,     yy = tensor([9, 0])
xx= tensor([[0.0852, 0.7634]]) ,     yy = tensor([0])


In [324]:
# x = [1,2,3,4,5,6] --> 무작위로 2개씩 추출하는 프로그램을 짜세요.
X = torch.tensor([1,2,3,4,5,6])
mydata = TensorDataset(X)
trainloader = DataLoader(dataset = mydata, batch_size=2, shuffle=True)

In [325]:
for xx in trainloader:
    print(xx)

[tensor([6, 3])]
[tensor([4, 1])]
[tensor([2, 5])]


(2) Pytorch Lab : Derivative

Determine the derivative of

$ y = 2x^3+x $   at   $x=1$.


In [328]:
x = torch.tensor(1., requires_grad=True) # 미분할 것들은 True로 설정해야해 #every operation on them should be tracked
y = 2 * x ** 3 + x
y.backward() # x로 미분할 거라 위에서 설정해놨기 때문에 x로 알아서 미분해 # calculate derivatives and stores them in the respective tensors' .grad 
x.grad

tensor(7.)

In [329]:
x = torch.tensor(1., requires_grad=True) #every operation on them should be tracked
y = 2 * x ** 3 + x
z = torch.exp(y)
z.backward()
x.grad  # np.exp(3)*7

tensor(140.5988)

In [330]:
print(x.data, x)

tensor(1.) tensor(1., requires_grad=True)


partial derivative  
1) $ f=uv+(uv)^2$
* Calculate grad of $u$ at $u=2$ and $v=1$: $ f=uv+(uv)^2$

In [332]:
# derivative of f = u * v + (u * v) ** 2 at u = 2, v = 1
# df/du = v + 2*u*v*v = 1+2*2*1*1=5, df/dv = u + 2*u*v*u = 2+2*2*1*2 = 10

u = torch.tensor(2., requires_grad=True)
v = torch.tensor(1., requires_grad=True)
y = u*v + (u*v)**2
y.backward()  # dy/du, dy/dv 를 (u,v)=(2,1)에서 계산해 어딘가에 저장
print(u.grad, v.grad)

tensor(5.) tensor(10.)


2) $y=\exp(2x_1)+x_2^2$.

* Calculate $\triangledown y = \left( \frac{\delta y}{\delta x_1},
\frac{\delta y}{\delta x_2} \right)$ at $x_1=1.0$ and $x_2=2.0$.

In [334]:
x = torch.tensor([1.0,2.0], requires_grad=True)
y = torch.exp(2*x[0])+x[1]**2
y.backward()
x.grad

tensor([14.7781,  4.0000])

3) $f(x_1, x_2)=(x_1+2x_2^3)^2$.

* Calculate grad $f$ at $(x_1, x_2)=(1,2)$.

In [336]:
x = torch.tensor([1.0, 2.0], requires_grad=True)
f = (x[0]+2*x[1]**3)**2
f.backward()
x.grad

tensor([ 34., 816.])

In [337]:
x = torch.tensor([[1.0, 2.0]], requires_grad=True)  # x를 matrix로 만들
f = (x[0,0]+2*x[0,1]**3)**2
f.backward()
x.grad

tensor([[ 34., 816.]])

4) $f(x)=x_1^2+2x_2$ and $g(t)=\begin{pmatrix} \sin(t) \\ \cos(t)\end{pmatrix}.$
* Calculate $ \frac{d}{dt} f(g(t))$ at $t = 1$

In [339]:
t = torch.tensor([1.0], requires_grad=True)
g = torch.stack([torch.sin(t), torch.cos(t)])  # torch.tensor로 이어주면 안돼 # torch.cat도 가능
f = g[0]**2 + 2*g[1]
f.backward()
t.grad

tensor([-0.7736])

In [340]:
t = torch.tensor([1.0], requires_grad=True)
g = [torch.sin(t), torch.cos(t)] # 그냥 list로 묶어줘도 돼
f = g[0]**2 + 2*g[1]
f.backward()
t.grad

tensor([-0.7736])